language: ruby

rvm:
  - 2.5

cache: bundler

addons:
  apt:
    packages:
      - shellcheck

before_install:
  - gem update --system
  - gem --version
  - gem update bundler
  - bundle --version

script:
  - bundle exec rake
