language: ruby

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: fase
      rvm: 2.5.0
    - os: osx
      osx_image: xcode9.2
      rvm: 2.5.0

cache:
  bundler: true
  directories:
    - $HOME/Library/Caches/Homebrew

addons:
  apt:
    packages:
      - shellcheck

before_install:
  - if test osx = "$TRAVIS_OS_NAME"; then brew install shellcheck; fi
  - git config --global user.name git-cococo
  - git config --global user.email git-cococo@example.org
  - gem update --system
  - gem --version
  - gem update bundler
  - bundle --version

script:
  - bundle exec rake
