name: windows

on:
  - push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache rubygems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-rubygems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-rubygems-
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Setup git
        run: |
          git config --global user.name git-cococo
          git config --global user.email git-cococo@example.org
          git config --global core.autocrlf false
      - name: Install dependencies
        run: |
          gem update --system
          gem install --no-document bundler -v $(sed -n -e '/^BUNDLED WITH$/, /^   / p' Gemfile.lock | tail -n1)
          bundle config --local path vendor/bundle
          bundle install --jobs $(nproc) --retry 3
      - name: Output versions
        run: |
          set -eux
          git version
          sh --version
          ruby --version
          gem --version
          bundle --version
          cmake --version
          shellcheck --version
      - name: Run test
        run: bundle exec rake test
